sonar.projectKey=shopping-cart
sonar.projectName=Shopping Cart
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.source=17

# JaCoCo \u8986\u76D6\u7387\u62A5\u544A\u8DEF\u5F84\uFF08\u5173\u952E\u914D\u7F6E\uFF09
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# JUnit \u6D4B\u8BD5\u62A5\u544A\u8DEF\u5F84
sonar.junit.reportPaths=target/surefire-reports